[package]
name = "ttyaskpass"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "ttyaskpass"

[dependencies]
rand = "*"
secstr = "*"
ansi_term = "*"
interactor = "*"
colorhash256 = "*"
