[package]
name = "ttyaskpass"
version = "1.2.1"
authors = ["quininer kel <quininer@live.com>"]
description = "a safely passphrase prompt library."
repository = "https://github.com/quininer/ttyaskpass"
keywords = [ "askpass", "getpass", "passphrase", "prompt" ]
documentation = "https://docs.rs/ttyaskpass/"
license = "MIT"
categories = [ "command-line-utilities" ]

[[bin]]
name = "ttyaskpass"
doc = false

[[bin]]
name = "ttypinentry"
doc = false
required-features = [ "pinentry" ]

[dependencies]
libc = "0.2"
rand = "0.3"
seckey = "0.5"
termion = "1.3"
tiny-keccak = "1.2"
nom = { version = "2.2", optional = true }
url = { version = "1.4", optional = true }

[features]
default = [ "pinentry" ]
pinentry = [ "nom", "url" ]
