[package]
name = "ttyaskpass"
version = "0.1.2"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "ttyaskpass"
doc = false

[dependencies]
libc = "0.2"
rand = "0.3"
seckey = "0.4"
termion = "1.2"
tiny-keccak = "1.2"
