[package]
name = "ttyaskpass"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "ttyaskpass"

[dependencies]
rand = "0.3"
sarkara = { git = "https://github.com/quininer/sarkara.git" }
ansi_term = "0.7"
interactor = "0.1"
colorhash256 = { git = "https://github.com/quininer/colorhash256.git", branch = "no_std" }
