[package]
name = "ttyaskpass"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[[bin]]
name = "ttyaskpass"

[dependencies]
rand = "0.3"
secstr = "0.2"
ansi_term = "0.7"
interactor = "0.1"
colorhash256 = "0.1"
