[package]
name = "ttyaskpass"
version = "1.0.1"
authors = ["quininer kel <quininer@live.com>"]
description = "a safely passphrase prompt library."
repository = "https://github.com/quininer/ttyaskpass"
keywords = [ "askpass", "getpass", "passphrase", "prompt" ]
documentation = "https://docs.rs/ttyaskpass/"
license = "MIT"

[[bin]]
name = "ttyaskpass"
doc = false

[dependencies]
libc = "0.2"
rand = "0.3"
seckey = "0.4"
termion = "1.2"
tiny-keccak = "1.2"
